# Generated by Django 2.2.16 on 2023-05-02 11:04

from django.contrib.sessions.models import Session
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    Session.objects.all().delete()
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя меню')),
                ('url', models.CharField(default=models.CharField(max_length=255, unique=True, verbose_name='Имя меню'), max_length=255, verbose_name='URL меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя подменю')),
                ('url', models.CharField(default=models.CharField(max_length=255, verbose_name='Имя подменю'), max_length=255, verbose_name='URL подменю')),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.Menu', verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='menu.Item', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
    ]
