# Generated by Django 3.2 on 2023-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_item_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.SlugField(default='default Menu name', max_length=255, verbose_name='URL меню'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(default='default Item name', max_length=255, verbose_name='Item url'),
        ),
    ]
