# Generated by Django 3.2 on 2023-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20230428_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(default=models.CharField(max_length=255, verbose_name='Название'), max_length=255, verbose_name='URL подменю'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default=models.CharField(max_length=255, unique=True, verbose_name='Название меню'), max_length=255, verbose_name='URL меню'),
        ),
    ]
